---
project: lib_xcore_math
title: XMath
version: 2.1.3

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  doxygen_projects:
    lib_xcore_math:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/programming_guide/index:
      pdf_title: "{{title}} - Programming Guide"
      pdf_filename: "{{project}}_programming_guide_v{{version}}"
