channels:
  - mvdbeek
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cmake=3.14.0
  - make=4.2.1
  - nbval=0.9.6
  - ncurses=6.1
  - python=3.6.8
  - pytest=5.2.0
  - pytest-forked=1.1.3
  - pytest-xdist=1.30.0
  - Sphinx==3.3.1
